outfile : main.o hist.o exec.o string_operations.o
	cc main.c hist.c exec.c string_operations.c -o shell

main.o : main.c
	cc -c main.c

hist.o : hist.c
	cc -c hist.c

exec.o : exec.c
	cc -c exec.c

string_operations.o : string_operations.c
	cc -c string_operations.c